# Generated by Django 3.2.2 on 2021-05-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_coefficient', models.IntegerField()),
                ('b_coefficient', models.IntegerField()),
            ],
        ),
    ]
