# Generated by Django 3.2.2 on 2021-05-15 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=255)),
                ('level_name', models.CharField(max_length=255)),
                ('level_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(null=True, verbose_name='date_published')),
                ('amount_paid', models.CharField(max_length=255, null=True)),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.space')),
            ],
        ),
    ]
