# Generated by Django 3.2.2 on 2021-05-15 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_motorcycle_spaces', models.IntegerField()),
                ('available_car_spaces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fill_priority', models.IntegerField()),
                ('available_spaces', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.avaliable')),
            ],
        ),
    ]
